workflows:
  android-build:
    name: Android Build
    scripts:
      - name: Build Web to APK
        script: |
          # استنساخ أداة التحويل
          git clone https://github.com/Jipok/website-to-apk.git
          cd website-to-apk
          
          # بناء التطبيق (استخدمت الرابط العام كمثال، يمكنك إعادته للرابط المحلي إذا كنت تختبر)
          ./gradlew assembleDebug -PappUrl="https://a51702dd-1333-42b7-8ff6-d744c8b30488-00-2wna80bpuhr6a.kirk.replit.dev" -PappName="Calculator" -PpackageName="com.hassan.calculator" -PversionCode="1" -PversionName="1.0"
          
          # إنشاء مجلد المخرجات
          mkdir -p $CM_ARTIFACT_PATH
          
          # --- هذا هو السطر الذي تم إصلاحه ---
          # نسخ ملف APK من مساره الصحيح داخل مجلد المشروع إلى مجلد المخرجات
          cp app/build/outputs/apk/debug/app-debug.apk $CM_ARTIFACT_PATH/hassan-calculator.apk

    artifacts:
      - $CM_ARTIFACT_PATH/*.apk

    publishing:
      email:
        recipients:
          - alkingbibi27@gmail.com # استبدل هذا ببريدك الإلكتروني
        notify:
          success: true
          failure: false
