workflows:
  android-build:
    name: Android Build
    scripts:
      - name: Install dependencies
        script: |
          pip3 install Flask
      - name: Build Web to APK
        script: |
          git clone https://github.com/Jipok/website-to-apk.git
          cd website-to-apk
          
          # --- التغيير الوحيد والمهم هنا ---
          # استخدام رابط Replit العام بدلاً من الرابط المحلي
          ./gradlew assembleDebug -PappUrl="https://a51702dd-1333-42b7-8ff6-d744c8b30488-00-2wna80bpuhr6a.kirk.replit.dev" -PappName="My App" -PpackageName="com.example.myapp" -PversionCode="1" -PversionName="1.0"
          
          # حفظ الملف الناتج
          mkdir -p $CM_ARTIFACT_PATH
          cp app/build/outputs/apk/debug/app-debug.apk $CM_ARTIFACT_PATH/app-debug.apk

    artifacts:
      - $CM_ARTIFACT_PATH/*.apk
