workflows:
  android-build:
    name: Android Build
    scripts:
      - name: Build Web to APK
        script: |
          # 1. استنساخ الأداة كما كنت تفعل
          git clone https://github.com/Jipok/website-to-apk.git
          cd website-to-apk

          # 2. بناء التطبيق باستخدام رابط Replit العام. هذا ضروري ليعمل التطبيق.
          ./gradlew assembleDebug -PappUrl="https://a51702dd-1333-42b7-8ff6-d744c8b30488-00-2wna80bpuhr6a.kirk.replit.dev" -PappName="Calculator" -PpackageName="com.hassan.calculator"

          # 3. نسخ ملف APK الناتج إلى مجلد المخرجات الخاص بـ Codemagic
          mkdir -p $CM_ARTIFACT_PATH
          cp app/build/outputs/apk/debug/app-debug.apk $CM_ARTIFACT_PATH/hassan-calculator.apk

    # 4. إخبار Codemagic بأن هناك ملفات ناتجة ليتم حفظها
    artifacts:
      - $CM_ARTIFACT_PATH/*.apk

    # 5. (اختياري) إرسال الملف الناتج إلى بريدك الإلكتروني بالطريقة الرسمية
    publishing:
      email:
        recipients:
          - alkingbibi27@gmail.com # يمكنك وضع بريدك هنا
        notify:
          success: true # إرسال فقط عند النجاح
