workflows:
  android-build:
    name: Android Build
    scripts:
      - name: Install Python and pip
        script: |
          pip3 install Flask
      - name: Build Web to APK
        script: |
          wget https://github.com/shrithan-reddy/Web-to-APK-Builder/raw/main/apk-builder-1.0.jar
          java -jar apk-builder-1.0.jar --package com.example.myapp --name "My App" --version "1.0" --url "https://your-flask-app-url.com" --output app-release.apk
      - name: Send email with APK
        script: |
          python3 send_email.py
