workflows:
  android-build:
    name: Android Build
    scripts:
      - name: Install dependencies
        script: |
          pip3 install Flask
      - name: Build Web to APK
        script: |
          git clone https://github.com/Jipok/website-to-apk.git
          cd website-to-apk
          ./gradlew assembleDebug -PappUrl="http://192.168.8.145:5000" -PappName="My App" -PpackageName="com.example.myapp" -PversionCode="1" -PversionName="1.0"
          mkdir -p $CM_OUTPUT_DIR
          cp app/build/outputs/apk/debug/app-debug.apk $CM_OUTPUT_DIR/app-debug.apk
      - name: Send email with APK
        script: |
          python3 send_email.py
